var fruits = ["mango", "banana", "watermelon", "kiwi"];
console.log("is 'apple' in fruits");
console.log(fruits.includes("apple"));
var colours = ["red", "green", "blue", "pink",];
console.log("is 'blue' in colours");
console.log(colours.includes("blue"));
var num = 6;
var nam1 = 7;
console.log(num != nam1);
console.log(5 < 7);
console.log(10 <= 17);
console.log(9 > 10);
var and = 6 < 8;
var and1 = 7 > 6;
console.log(and && and1);
var and3 = 9 < 8;
var and4 = 7 < 9;
console.log(and3 && and4);
var and5 = 10 == 10;
var and6 = 10 != 10;
console.log(and5 || and6);
var and7 = 7 > 9;
var and8 = 4 < 5;
console.log(and7 != and8);
